#!/usr/bin/env bash
# Kill the process with the name "4-to_infinity_and_beyond"
#   This script assumes that the process with the name
#   "4-to_infinity_and_beyond" is currently running.
kill "$(pgrep -f ./4-to_infinity_and_beyond)"
