#!/usr/bin/env bash
# This script sets a trap for the SIGTERM signal. When the SIGTERM signal is
# received, the script will echo "I am invincible!!!"

# Set a trap for the SIGTERM signal
trap "echo I am invincible!!!" SIGTERM

# Continuously print "To infinity and beyond" every 2 seconds
while true; do
    # Print "To infinity and beyond"
    echo "To infinity and beyond"

    # Sleep for 2 seconds
    sleep 2
done
